name: Fetcher

on:
  push:
  schedule:
    - cron: '0 15 * * *'
  workflow_dispatch:

jobs:
  fetch:
    name: rfcsubseries rfc fetching
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.0
      - name: Install gem
        run: |
          gem install relaton-cli
      - name: Fetch documents
        run: |
          rm -rf data
          relaton fetch-data ietf-rfc-entries
      - name: Push data
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add data
          git diff --quiet && git diff --staged --quiet || (git commit -m 'update documents' && git push)
      - uses: gautamkrishnar/keepalive-workflow@v1
        with:
          commiter_username: github-actions
          commiter_email: github-actions@github.com
